import Testing
import Foundation
@testable import Models

@Test func noteInitialization() {
    let note = Note(bodyMarkdown: "Hello world")
    #expect(note.title == "Hello world")
    #expect(note.bodyMarkdown == "Hello world")
    #expect(note.isPinned == false)
    #expect(note.isTrashed == false)
    #expect(note.wordCount == 2)
    #expect(note.characterCount == 11)
}

@Test func noteWordCountUpdate() {
    let note = Note(bodyMarkdown: "one two three")
    note.bodyMarkdown = "just one"
    note.updateWordCount()
    #expect(note.wordCount == 2)
    #expect(note.characterCount == 8)
}

@Test func titleAutoGeneratedFromBody() {
    let longBody = String(repeating: "a", count: 100)
    let note = Note(bodyMarkdown: longBody)
    #expect(note.title.count == 50)
    #expect(note.title == String(repeating: "a", count: 50))
}

@Test func titleSyncsOnWordCountUpdate() {
    let note = Note(bodyMarkdown: "original text")
    #expect(note.title == "original text")
    note.bodyMarkdown = "updated body content that is quite long and exceeds fifty characters total"
    note.updateWordCount()
    #expect(note.title == String("updated body content that is quite long and exceed".prefix(50)))
    #expect(note.title.count == 50)
}

@Test func emptyBodyGivesEmptyTitle() {
    let note = Note()
    #expect(note.title == "")
    #expect(note.bodyMarkdown == "")
    #expect(note.wordCount == 0)
}
